[package]
name = "async_future_example"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8"
futures = "0.3"
jammdb = "0.1"
smol = "1.2"
rmp-serde = "1.0" 
async-std = "1.10"
indicatif = "0.16"
dashmap = "5.0"